### Importing Numpy

In [1]:
import numpy as np

### Basics

In [4]:
a = np.array([1,2,3,4], dtype="float")
print(a)

[1. 2. 3. 4.]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimension
a.ndim

1

In [7]:
# Get Shape
b.shape

(2, 3)

In [8]:
# Get Type
a.dtype

dtype('float64')

In [9]:
# Get Size
a.itemsize

8

In [10]:
# Get total size
a.nbytes

32

### Indexing/Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c]
a[1, 5]

13

In [13]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific col 
a[:, 3]

array([ 4, 11])

In [16]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
# row : start : end : stepsize

array([2, 4, 6])

In [18]:
a[1,5] = 20
a[:,2] = [1,2]  # change 2nd col of row - 0,1 to [1,2] 
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


#### *3-d example

In [24]:
b = np.array([  [[1,2],[3,4]],  [[5,6],[7,8]]  ])
print(b.shape)
print(b)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# get specific element in 3-D array
# if we want to get 4, follow outter to inner rule
# 1st 2d array -> 2nd Row -> 2nd Cols
b[0,1:,1:]

array([[4]])

In [27]:
# get specific element in 3-D array
# if we want to get 4, follow outter to inner rule
# 1st 2d array -> 2nd Row -> 2nd Cols
b[0,1:,:] = [90,99]
b

array([[[ 1,  2],
        [90, 99]],

       [[ 5,  6],
        [ 7,  8]]])

### How to Intialize different Arrays

In [36]:
# Intializing Array of default 0 Value. with "zeros"
z = np.zeros((4,2))
print("Default dtype is float : ", "\n", z)
z = np.zeros((4,2), dtype="int32")
print("Set dtype to Int32 : ", "\n", z)

Default dtype is float :  
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Set dtype to Int32 :  
 [[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [37]:
# Intializing Array of default 0 Value. with "ones"
one = np.ones((4,2))
print("Default dtype is float : ", "\n", one)
one = np.ones((4,2), dtype="int32")
print("Set dtype to Int32 : ", "\n", one)

Default dtype is float :  
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Set dtype to Int32 :  
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [38]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [41]:
# Any other number (full_like)
np.full_like(a, 4)

#  a = [[ 1  2  1  4  5  6  7]
#     [ 8  9  2 11 12 20 14]]

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
# Random decimal numbers
# np.random.rand(rows, colms) Random Decimal Number
np.random.rand(4,2)

array([[0.77243418, 0.07072297],
       [0.39292062, 0.08032454],
       [0.18362177, 0.3132192 ],
       [0.60947862, 0.77441728]])

In [50]:
# Random Integer numbers
# np.random.RANDINT(start, end-1, size of matrix in tuple) Random Integer Number
np.random.randint(0,4, size=(2,2))

array([[0, 3],
       [2, 0]])

In [51]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# Repeat an array
arr = np.array([[1,2,3]])
# print(arr.shape)   (1, 3)
# print(arr)     [[1 2 3]]
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [66]:
#  How can we Intialize a array like this?
#   [[1. 1. 1. 1. 1.]
#    [1. 0. 0. 0. 1.]
#    [1. 0. 9. 0. 1.]
#    [1. 0. 0. 0. 1.]
#    [1. 1. 1. 1. 1.]]

output = np.ones((5,5))
zero = np.zeros((3,3))
zero[1:2,1:2] = 9

output[1:4,1:4] = zero
print(output)


# output = np.ones((5,5))
# print(output)

# z = np.zeros((3,3))
# z[1,1] = 9
# print(z)

# output[1:-1,1:-1] = z
# print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Copy : Be Careful while copying, Because by default copy is shallow. i.e. only reference is made


In [68]:
a = np.array([1,2,3])
b = a.copy() # use .copy fuction
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [69]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [70]:
a + 2

array([3, 4, 5, 6])

In [71]:
a - 2

array([-1,  0,  1,  2])

In [72]:
a * 3

array([ 3,  6,  9, 12])

In [73]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
a // 2

array([0, 1, 1, 2], dtype=int32)

In [75]:
b = np.array([7,8,9,10])

In [76]:
a + b

array([ 8, 10, 12, 14])

In [77]:
a * b

array([ 7, 16, 27, 40])

In [78]:
a / b

array([0.14285714, 0.25      , 0.33333333, 0.4       ])

In [82]:
# make square
a ** 2

array([ 1,  4,  9, 16])

In [83]:
# Take Cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [84]:
# Take Sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [86]:
# matmul to Multiply Matrix Multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [87]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
##### Determinant, Trace, Singular Vector Decomposition, Eigenvalues, Matrix Norm, Inverse, Etc...

### Statistics

In [88]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.min(stats)

1

In [90]:
np.max(stats)

6

In [91]:
np.min(stats, axis=1)

array([1, 4])

In [92]:
np.max(stats, axis=0)

array([4, 5, 6])

### Reorganizing Arrays

In [96]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2)) # Number of elements should be equals
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [97]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
# Horizontal stacking vectors
v1 = np.ones((2,2))
v2 = np.zeros((2,2))

np.hstack([v1,v2,v1,v2])

array([[1., 1., 0., 0., 1., 1., 0., 0.],
       [1., 1., 0., 0., 1., 1., 0., 0.]])

### Miscellaneous
Load Data from File

In [102]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advanced Indexing

In [103]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [105]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [106]:
filedata[filedata < 50]

array([ 1, 13, 21, 11,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,  4,  5,  3,
       42, 12, 33,  4,  6,  4,  3,  4,  5,  6,  7,  0, 11, 12,  1, 22, 33,
       11, 11,  2,  1,  0,  1,  2,  9,  8,  7,  1])

In [107]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])